Проектная работа 12, создание сервера для проекта Mesto.
ko1p/node_one pull request #1
Opened 2020-05-01 08:04 UTC by ko1p

Выполнил все требования по заданию, сверился по чек листу, пока все ок :)

2020-05-02 05:19 UTC, mrprovoker requested changes
Добрый день!

Работа в целом хорошая, большинство проверок реализованные роуты проходит, отличное README, код аккуратный и чистый. Но есть несколько критичных замечаний.

**Надо исправить:**
- Если запустить `eslint --ext=.js ./`, исключая проверку директорий node_modules и public, то будет 16 ошибок линтинга. Ошибок быть не должно.
- Некорректно обрабатывается POST-запрос `http://localhost:3000/users/123`. Сейчас ответ приходит в виде HTML, а ожидается ответ в виде JSON: `{ message: 'Запрашиваемый ресурс не найден' }`. Аналогично и DELETE, PATCH и другие не GET-запросы. 
- Логически роут:
```
usersRouter.get('*', (req, res) => {
  res.status(404).send({ "message": "Запрашиваемый ресурс не найден" });
});
```
не относится к users. Он относится к приложению и лучше записать в app.js после подключения других роутов.
- Сейчас, если в запросе `/users/:id` пользователь нашелся, то в консоле может возникать ошибка `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`. Ошибок быть не должно


Можно лучше:
- Рекомендуется заполнить description в package.json
- Согласно логике текущего файла `app.js` если прийдет запрос /users, то он сначала пойдет в Router cards, пройдется по всем роутам, не найдет там нужного маршрута и после этого пойдет обходить Router users.

Более оптимально будет заранее (первым аргументом) по началу запросов объявлять принадлежность к конкретному маршрутизатору, примерно так:

```
app.use('/cards', cardsRouter);
app.use('/users', usersRouter);
```
Соответственно в самих маршрутах в файлах будет необходимо убрать начало запроса.



При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-05-02 11:02 UTC, ko1p commented
Исправил

2020-05-03 06:14 UTC, mrprovoker approved these changes
Спасибо за правки. Теперь все отлично.

Все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

2020-05-03 06:14 UTC, mrprovoker commented on app.js
> +  // console.log(`Сервер запущен на ${PORT} порту`);
Можно лучше:
- Не рекомендуется в коде иметь закомментированный код. Строчку `console.log(`App listening ${PORT}`);` можно раскомментировать.

2021-04-04 09:34 UTC, merged